export const categories = [
  'Văn học',
  'Kinh tế',
  'Thiếu nhi',
  'Kỹ năng sống',
  'Truyện tranh',
  'Ngoại ngữ',
];

export const books = [
  {
    id: '1',
    title: 'Nhà giả kim',
    author: 'Paulo Coelho',
    price: 79000,
    oldPrice: 99000,
    category: 'Văn học',
    badge: '-20%',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600',
    description: 'Nhà giả kim là câu chuyện giàu tính biểu tượng về hành trình theo đuổi ước mơ và lắng nghe tiếng gọi của trái tim. Cuốn sách truyền cảm hứng để mỗi người can đảm bước ra khỏi vùng an toàn, học hỏi từ những thất bại và nhận ra kho báu thật sự thường nằm ngay trên hành trình.',
  },
  {
    id: '2',
    title: 'Đắc nhân tâm',
    author: 'Dale Carnegie',
    price: 86000,
    oldPrice: 105000,
    category: 'Kỹ năng sống',
    badge: 'Mới',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600',
    description: 'Những nguyên tắc giao tiếp và ứng xử kinh điển giúp bạn hiểu người khác, xây dựng mối quan hệ tốt đẹp và phát triển bản thân trong công việc cũng như cuộc sống.',
  },
  {
    id: '3',
    title: 'Tuổi trẻ đáng giá bao nhiêu',
    author: 'Rosie Nguyễn',
    price: 72000,
    category: 'Kỹ năng sống',
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600',
    description: 'Một cuốn sách gần gũi dành cho người trẻ đang tìm kiếm hướng đi, muốn học tập chủ động, trải nghiệm nhiều hơn và sống một tuổi trẻ có ý nghĩa.',
  },
  {
    id: '4',
    title: 'Dế Mèn phiêu lưu ký',
    author: 'Tô Hoài',
    price: 55000,
    oldPrice: 65000,
    category: 'Thiếu nhi',
    badge: '-15%',
    image: 'https://images.unsplash.com/photo-1629992101753-56d196c8aabb?w=600',
    description: 'Tác phẩm thiếu nhi kinh điển kể về những chuyến phiêu lưu đầy thú vị của Dế Mèn, đồng thời gửi gắm bài học về tình bạn, lòng dũng cảm và trách nhiệm.',
  },
  {
    id: '5',
    title: 'Nghệ thuật tinh tế của việc đếch quan tâm',
    author: 'Mark Manson',
    price: 99000,
    category: 'Kỹ năng sống',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600',
    description: 'Góc nhìn thẳng thắn và thực tế về cách lựa chọn điều đáng quan tâm, chấp nhận giới hạn và sống một cuộc đời chân thật hơn.',
  },
  {
    id: '6',
    title: 'Cà phê cùng Tony',
    author: 'Tony Buổi Sáng',
    price: 88000,
    oldPrice: 110000,
    category: 'Kinh tế',
    badge: '-20%',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600',
    description: 'Những câu chuyện ngắn, dí dỏm và nhiều năng lượng về thái độ sống, tinh thần khởi nghiệp và cách rèn luyện bản thân của người trẻ.',
  },
];

export const cartItems = [
  { ...books[0], quantity: 1 },
  { ...books[2], quantity: 2 },
  { ...books[5], quantity: 1 },
];
